import type {
  Stat,
  RevenuePoint,
  CategoryPoint,
  Transaction,
  Customer,
  Product,
  Notification,
  CustomerGrowthPoint,
  ProductPerformancePoint,
  DateRange,
} from './types';

export const stats: Stat[] = [
  {
    label: 'Total Revenue',
    value: 284523,
    previousValue: 248290,
    changePercent: 14.58,
    format: 'currency',
    icon: 'revenue',
  },
  {
    label: 'Total Sales',
    value: 3874,
    previousValue: 3412,
    changePercent: 13.54,
    format: 'number',
    icon: 'sales',
  },
  {
    label: 'Total Customers',
    value: 2847,
    previousValue: 2615,
    changePercent: 8.87,
    format: 'number',
    icon: 'customers',
  },
  {
    label: 'Conversion Rate',
    value: 3.42,
    previousValue: 2.81,
    changePercent: 21.71,
    format: 'percent',
    icon: 'conversion',
  },
];

function generateRevenueData(range: DateRange): RevenuePoint[] {
  const configs: Record<DateRange, { points: number; interval: number }> = {
    '7d': { points: 7, interval: 1 },
    '30d': { points: 30, interval: 1 },
    '90d': { points: 12, interval: 7 },
    '12m': { points: 12, interval: 30 },
  };

  const { points, interval } = configs[range];
  const data: RevenuePoint[] = [];
  const now = new Date();

  let baseRevenue = 8000;
  let baseSales = 120;

  for (let i = points - 1; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i * interval);

    const seasonal = Math.sin((i / points) * Math.PI * 2) * 1500;
    const trend = (points - i) * 80;
    const noise = (Math.random() - 0.5) * 2000;

    const revenue = Math.max(3000, Math.round(baseRevenue + seasonal + trend + noise));
    const sales = Math.max(40, Math.round(baseSales + seasonal / 20 + trend / 12 + (Math.random() - 0.5) * 30));

    data.push({
      date: date.toISOString().split('T')[0],
      revenue,
      sales,
    });
  }

  return data;
}

export function getRevenueData(range: DateRange): RevenuePoint[] {
  return generateRevenueData(range);
}

export const categoryData: CategoryPoint[] = [
  { category: 'Electronics', sales: 1240, color: 'hsl(var(--chart-1))' },
  { category: 'Apparel', sales: 890, color: 'hsl(var(--chart-2))' },
  { category: 'Home & Living', sales: 670, color: 'hsl(var(--chart-3))' },
  { category: 'Sports', sales: 540, color: 'hsl(var(--chart-4))' },
  { category: 'Books', sales: 334, color: 'hsl(var(--chart-5))' },
];

export const transactions: Transaction[] = [
  {
    id: 'TXN-1001',
    customerName: 'Sarah Chen',
    customerEmail: 'sarah.chen@email.com',
    customerAvatar: 'SC',
    product: 'Wireless Noise-Cancelling Headphones',
    amount: 299.99,
    status: 'completed',
    date: '2026-09-12T10:30:00Z',
  },
  {
    id: 'TXN-1002',
    customerName: 'Marcus Johnson',
    customerEmail: 'm.johnson@email.com',
    customerAvatar: 'MJ',
    product: 'Smart Fitness Watch Pro',
    amount: 199.5,
    status: 'completed',
    date: '2026-09-12T08:15:00Z',
  },
  {
    id: 'TXN-1003',
    customerName: 'Elena Rodriguez',
    customerEmail: 'elena.r@email.com',
    customerAvatar: 'ER',
    product: 'Organic Cotton Hoodie',
    amount: 78.0,
    status: 'pending',
    date: '2026-09-11T16:45:00Z',
  },
  {
    id: 'TXN-1004',
    customerName: 'David Kim',
    customerEmail: 'david.kim@email.com',
    customerAvatar: 'DK',
    product: 'Bluetooth Portable Speaker',
    amount: 149.99,
    status: 'completed',
    date: '2026-09-11T14:20:00Z',
  },
  {
    id: 'TXN-1005',
    customerName: 'Priya Patel',
    customerEmail: 'priya.p@email.com',
    customerAvatar: 'PP',
    product: 'Ceramic Coffee Mug Set',
    amount: 42.5,
    status: 'failed',
    date: '2026-09-11T11:00:00Z',
  },
  {
    id: 'TXN-1006',
    customerName: 'James Wilson',
    customerEmail: 'j.wilson@email.com',
    customerAvatar: 'JW',
    product: '4K Action Camera',
    amount: 449.0,
    status: 'completed',
    date: '2026-09-10T19:30:00Z',
  },
  {
    id: 'TXN-1007',
    customerName: 'Aisha Mohammed',
    customerEmail: 'aisha.m@email.com',
    customerAvatar: 'AM',
    product: 'Yoga Mat Premium',
    amount: 65.0,
    status: 'pending',
    date: '2026-09-10T15:10:00Z',
  },
  {
    id: 'TXN-1008',
    customerName: 'Thomas Anderson',
    customerEmail: 't.anderson@email.com',
    customerAvatar: 'TA',
    product: 'Mechanical Keyboard RGB',
    amount: 189.99,
    status: 'completed',
    date: '2026-09-10T09:25:00Z',
  },
  {
    id: 'TXN-1009',
    customerName: 'Lisa Wang',
    customerEmail: 'lisa.w@email.com',
    customerAvatar: 'LW',
    product: 'Stainless Steel Water Bottle',
    amount: 28.0,
    status: 'completed',
    date: '2026-09-09T17:40:00Z',
  },
  {
    id: 'TXN-1010',
    customerName: 'Oliver Smith',
    customerEmail: 'oliver.s@email.com',
    customerAvatar: 'OS',
    product: 'Wireless Charging Pad',
    amount: 39.99,
    status: 'failed',
    date: '2026-09-09T13:55:00Z',
  },
  {
    id: 'TXN-1011',
    customerName: 'Nina Rossi',
    customerEmail: 'nina.rossi@email.com',
    customerAvatar: 'NR',
    product: 'Running Shoes Elite',
    amount: 159.0,
    status: 'completed',
    date: '2026-09-08T20:15:00Z',
  },
  {
    id: 'TXN-1012',
    customerName: 'Carlos Gomez',
    customerEmail: 'c.gomez@email.com',
    customerAvatar: 'CG',
    product: 'Smart LED Desk Lamp',
    amount: 89.99,
    status: 'pending',
    date: '2026-09-08T10:30:00Z',
  },
  {
    id: 'TXN-1013',
    customerName: 'Hannah Schmidt',
    customerEmail: 'hannah.s@email.com',
    customerAvatar: 'HS',
    product: 'Leather Laptop Backpack',
    amount: 129.0,
    status: 'completed',
    date: '2026-09-07T18:00:00Z',
  },
  {
    id: 'TXN-1014',
    customerName: 'Ryan Taylor',
    customerEmail: 'ryan.t@email.com',
    customerAvatar: 'RT',
    product: 'USB-C Hub 8-in-1',
    amount: 59.99,
    status: 'completed',
    date: '2026-09-07T12:45:00Z',
  },
  {
    id: 'TXN-1015',
    customerName: 'Mei Lin',
    customerEmail: 'mei.lin@email.com',
    customerAvatar: 'ML',
    product: 'Bamboo Cutlery Travel Set',
    amount: 24.5,
    status: 'pending',
    date: '2026-09-06T16:20:00Z',
  },
  {
    id: 'TXN-1016',
    customerName: 'Daniel Foster',
    customerEmail: 'd.foster@email.com',
    customerAvatar: 'DF',
    product: 'Ergonomic Office Chair',
    amount: 449.0,
    status: 'completed',
    date: '2026-09-06T09:00:00Z',
  },
  {
    id: 'TXN-1017',
    customerName: 'Sofia Garcia',
    customerEmail: 'sofia.g@email.com',
    customerAvatar: 'SG',
    product: 'Natural Skincare Bundle',
    amount: 95.0,
    status: 'failed',
    date: '2026-09-05T21:30:00Z',
  },
  {
    id: 'TXN-1018',
    customerName: 'Kevin Nguyen',
    customerEmail: 'k.nguyen@email.com',
    customerAvatar: 'KN',
    product: 'Gaming Mouse Wireless',
    amount: 79.99,
    status: 'completed',
    date: '2026-09-05T14:10:00Z',
  },
  {
    id: 'TXN-1019',
    customerName: 'Amber Hill',
    customerEmail: 'amber.h@email.com',
    customerAvatar: 'AH',
    product: 'Linen Bedding Set Queen',
    amount: 175.0,
    status: 'pending',
    date: '2026-09-04T11:50:00Z',
  },
  {
    id: 'TXN-1020',
    customerName: 'Ibrahim Khalil',
    customerEmail: 'i.khalil@email.com',
    customerAvatar: 'IK',
    product: 'Portable Power Bank 20K',
    amount: 49.99,
    status: 'completed',
    date: '2026-09-04T07:30:00Z',
  },
];

export const customers: Customer[] = [
  {
    id: 'CUS-001',
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    avatar: 'SC',
    status: 'active',
    totalSpending: 4520.5,
    orders: 28,
    joinedDate: '2024-03-15',
    location: 'San Francisco, CA',
  },
  {
    id: 'CUS-002',
    name: 'Marcus Johnson',
    email: 'm.johnson@email.com',
    avatar: 'MJ',
    status: 'active',
    totalSpending: 3210.0,
    orders: 19,
    joinedDate: '2024-06-22',
    location: 'New York, NY',
  },
  {
    id: 'CUS-003',
    name: 'Elena Rodriguez',
    email: 'elena.r@email.com',
    avatar: 'ER',
    status: 'active',
    totalSpending: 2890.75,
    orders: 22,
    joinedDate: '2024-01-08',
    location: 'Austin, TX',
  },
  {
    id: 'CUS-004',
    name: 'David Kim',
    email: 'david.kim@email.com',
    avatar: 'DK',
    status: 'inactive',
    totalSpending: 1450.0,
    orders: 11,
    joinedDate: '2024-08-30',
    location: 'Seattle, WA',
  },
  {
    id: 'CUS-005',
    name: 'Priya Patel',
    email: 'priya.p@email.com',
    avatar: 'PP',
    status: 'active',
    totalSpending: 5680.25,
    orders: 35,
    joinedDate: '2023-11-12',
    location: 'Chicago, IL',
  },
  {
    id: 'CUS-006',
    name: 'James Wilson',
    email: 'j.wilson@email.com',
    avatar: 'JW',
    status: 'churned',
    totalSpending: 890.0,
    orders: 5,
    joinedDate: '2024-09-05',
    location: 'Boston, MA',
  },
  {
    id: 'CUS-007',
    name: 'Aisha Mohammed',
    email: 'aisha.m@email.com',
    avatar: 'AM',
    status: 'active',
    totalSpending: 3750.5,
    orders: 24,
    joinedDate: '2024-02-18',
    location: 'Denver, CO',
  },
  {
    id: 'CUS-008',
    name: 'Thomas Anderson',
    email: 't.anderson@email.com',
    avatar: 'TA',
    status: 'active',
    totalSpending: 6230.0,
    orders: 41,
    joinedDate: '2023-09-14',
    location: 'Portland, OR',
  },
  {
    id: 'CUS-009',
    name: 'Lisa Wang',
    email: 'lisa.w@email.com',
    avatar: 'LW',
    status: 'inactive',
    totalSpending: 1120.0,
    orders: 8,
    joinedDate: '2024-07-01',
    location: 'Los Angeles, CA',
  },
  {
    id: 'CUS-010',
    name: 'Oliver Smith',
    email: 'oliver.s@email.com',
    avatar: 'OS',
    status: 'active',
    totalSpending: 2890.0,
    orders: 17,
    joinedDate: '2024-04-20',
    location: 'Miami, FL',
  },
  {
    id: 'CUS-011',
    name: 'Nina Rossi',
    email: 'nina.rossi@email.com',
    avatar: 'NR',
    status: 'active',
    totalSpending: 4100.75,
    orders: 26,
    joinedDate: '2024-05-10',
    location: 'Phoenix, AZ',
  },
  {
    id: 'CUS-012',
    name: 'Carlos Gomez',
    email: 'c.gomez@email.com',
    avatar: 'CG',
    status: 'churned',
    totalSpending: 540.0,
    orders: 3,
    joinedDate: '2024-10-15',
    location: 'Dallas, TX',
  },
];

export const products: Product[] = [
  {
    id: 'PRD-001',
    name: 'Wireless Noise-Cancelling Headphones',
    category: 'Electronics',
    price: 299.99,
    stock: 142,
    stockStatus: 'in_stock',
    sales: 856,
    image: 'headphones',
    sku: 'ELEC-WH-001',
  },
  {
    id: 'PRD-002',
    name: 'Smart Fitness Watch Pro',
    category: 'Electronics',
    price: 199.5,
    stock: 89,
    stockStatus: 'in_stock',
    sales: 634,
    image: 'watch',
    sku: 'ELEC-SW-002',
  },
  {
    id: 'PRD-003',
    name: 'Organic Cotton Hoodie',
    category: 'Apparel',
    price: 78.0,
    stock: 12,
    stockStatus: 'low_stock',
    sales: 445,
    image: 'hoodie',
    sku: 'APP-HD-003',
  },
  {
    id: 'PRD-004',
    name: 'Bluetooth Portable Speaker',
    category: 'Electronics',
    price: 149.99,
    stock: 67,
    stockStatus: 'in_stock',
    sales: 523,
    image: 'speaker',
    sku: 'ELEC-BS-004',
  },
  {
    id: 'PRD-005',
    name: 'Ceramic Coffee Mug Set',
    category: 'Home & Living',
    price: 42.5,
    stock: 0,
    stockStatus: 'out_of_stock',
    sales: 312,
    image: 'mug',
    sku: 'HOME-CM-005',
  },
  {
    id: 'PRD-006',
    name: '4K Action Camera',
    category: 'Electronics',
    price: 449.0,
    stock: 34,
    stockStatus: 'in_stock',
    sales: 289,
    image: 'camera',
    sku: 'ELEC-AC-006',
  },
  {
    id: 'PRD-007',
    name: 'Yoga Mat Premium',
    category: 'Sports',
    price: 65.0,
    stock: 8,
    stockStatus: 'low_stock',
    sales: 401,
    image: 'yogamat',
    sku: 'SPT-YM-007',
  },
  {
    id: 'PRD-008',
    name: 'Mechanical Keyboard RGB',
    category: 'Electronics',
    price: 189.99,
    stock: 56,
    stockStatus: 'in_stock',
    sales: 367,
    image: 'keyboard',
    sku: 'ELEC-KB-008',
  },
  {
    id: 'PRD-009',
    name: 'Stainless Steel Water Bottle',
    category: 'Home & Living',
    price: 28.0,
    stock: 215,
    stockStatus: 'in_stock',
    sales: 678,
    image: 'bottle',
    sku: 'HOME-WB-009',
  },
  {
    id: 'PRD-010',
    name: 'Running Shoes Elite',
    category: 'Sports',
    price: 159.0,
    stock: 23,
    stockStatus: 'in_stock',
    sales: 512,
    image: 'shoes',
    sku: 'SPT-RS-010',
  },
  {
    id: 'PRD-011',
    name: 'Wireless Charging Pad',
    category: 'Electronics',
    price: 39.99,
    stock: 0,
    stockStatus: 'out_of_stock',
    sales: 445,
    image: 'charger',
    sku: 'ELEC-CP-011',
  },
  {
    id: 'PRD-012',
    name: 'Leather Laptop Backpack',
    category: 'Apparel',
    price: 129.0,
    stock: 41,
    stockStatus: 'in_stock',
    sales: 298,
    image: 'backpack',
    sku: 'APP-BP-012',
  },
];

export const notifications: Notification[] = [
  {
    id: 'N-001',
    title: 'New order received',
    description: 'Sarah Chen placed an order for $299.99',
    time: '2026-09-12T10:30:00Z',
    read: false,
    type: 'order',
  },
  {
    id: 'N-002',
    title: 'Low stock alert',
    description: 'Organic Cotton Hoodie is running low on stock (12 left)',
    time: '2026-09-12T08:00:00Z',
    read: false,
    type: 'alert',
  },
  {
    id: 'N-003',
    title: 'Payment failed',
    description: 'Transaction TXN-1005 failed to process',
    time: '2026-09-11T11:05:00Z',
    read: false,
    type: 'alert',
  },
  {
    id: 'N-004',
    title: 'New customer registered',
    description: 'Ibrahim Khalil created an account',
    time: '2026-09-10T14:20:00Z',
    read: true,
    type: 'customer',
  },
  {
    id: 'N-005',
    title: 'Weekly report available',
    description: 'Your weekly analytics summary is ready to view',
    time: '2026-09-09T09:00:00Z',
    read: true,
    type: 'system',
  },
];

export const customerGrowthData: CustomerGrowthPoint[] = [
  { month: 'Oct', newCustomers: 180, totalCustomers: 2103 },
  { month: 'Nov', newCustomers: 205, totalCustomers: 2308 },
  { month: 'Dec', newCustomers: 312, totalCustomers: 2620 },
  { month: 'Jan', newCustomers: 148, totalCustomers: 2768 },
  { month: 'Feb', newCustomers: 172, totalCustomers: 2940 },
  { month: 'Mar', newCustomers: 195, totalCustomers: 3135 },
  { month: 'Apr', newCustomers: 168, totalCustomers: 3303 },
  { month: 'May', newCustomers: 210, totalCustomers: 3513 },
  { month: 'Jun', newCustomers: 189, totalCustomers: 3702 },
  { month: 'Jul', newCustomers: 225, totalCustomers: 3927 },
  { month: 'Aug', newCustomers: 248, totalCustomers: 4175 },
  { month: 'Sep', newCustomers: 267, totalCustomers: 4442 },
];

export const productPerformanceData: ProductPerformancePoint[] = [
  { name: 'Headphones', sales: 856, revenue: 256791 },
  { name: 'Fitness Watch', sales: 634, revenue: 126483 },
  { name: 'Water Bottle', sales: 678, revenue: 18984 },
  { name: 'Speaker', sales: 523, revenue: 78445 },
  { name: 'Running Shoes', sales: 512, revenue: 81408 },
  { name: 'Hoodie', sales: 445, revenue: 34710 },
  { name: 'Charging Pad', sales: 445, revenue: 17795 },
  { name: 'Yoga Mat', sales: 401, revenue: 26065 },
  { name: 'Keyboard', sales: 367, revenue: 69686 },
  { name: 'Mug Set', sales: 312, revenue: 13260 },
];

export const dateRangeLabels: Record<DateRange, string> = {
  '7d': 'Last 7 days',
  '30d': 'Last 30 days',
  '90d': 'Last 90 days',
  '12m': 'Last 12 months',
};
